#  https://qiita.com/A-Kira/items/f401aea261693c395966

version: '3'

services:
  # PHP
  php-app:
    container_name: php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    tty: true
    volumes:
      #      - ${PWD}:/var/www/html
      - ./docker/php/test:/var/www/html
    ports:
      - "8080:80"
    network_mode: "sample-network5"

  # MySQL
  db:
    image: mysql:8.0
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    tty: true
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    network_mode: "sample-network5"

networks:
  sample-network5: